USE DATABASE AIRLINE_DWH;
USE SCHEMA RAW_DATA;

-- Format CSV
CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', '');

-- Stage
CREATE OR REPLACE STAGE MY_INTERNAL_STAGE
  FILE_FORMAT = MY_CSV_FORMAT;