-- imitation: drop the base
DROP TABLE AIRLINE_DWH.GOLD_DATA.FLIGHTS_BY_COUNTRY_REPORT;

-- Restore deleted table with all data
UNDROP TABLE AIRLINE_DWH.GOLD_DATA.FLIGHTS_BY_COUNTRY_REPORT;

-- Create backup table passengers from its version 10 min ago
CREATE TABLE AIRLINE_DWH.SILVER_DATA.DIM_PASSENGERS_BACKUP 
CLONE AIRLINE_DWH.SILVER_DATA.DIM_PASSENGERS AT(OFFSET => -600);

-- Check its creating:
SELECT count(*) FROM AIRLINE_DWH.SILVER_DATA.DIM_PASSENGERS_BACKUP;